'''
Description  : Memory-safe FEC transition annotation. This script reads the
               dataframe generated by batch_fec_postprocess, detects transition
               indexes using numerical-derivative peaks or an HMM contour-length
               trace, manually curates transitions and states, calculates the
               extension associated with each transition, and writes the final
               annotation dataframe.

               Only one FEC is kept in memory at a time. Exact manual results
               are checkpointed after every FEC; whole-session dill files are
               not used.

Author       : Gabriel Jiménez-Avalos, Ph.D. student
Affiliation  : T. C. Jenkins Department of Biophysics, Johns Hopkins University
Version      : 4.0
Date         : 2026/09/11
'''


# %% CLEAN SESSION BEFORE START

try:
    from IPython import get_ipython
except ImportError:
    get_ipython = None

_ipython = get_ipython() if get_ipython is not None else None
if _ipython is not None:
    _ipython.run_line_magic("reset", "-sf")


# %% IMPORT MODULES

import gc
import hashlib
import json
import os
import sys
from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# %% IMPORT CUSTOM MODULES

sys.path.insert(1, '/Users/gabriel/scripts/optical_tweezers_toolbox')
from tweezers_toolbox_modules.preprocessing import CK_filtfilt
from tweezers_toolbox_modules import analysis as ana
from tweezers_toolbox_modules import fec_plotting as fplt

# %% DEFINE FUNCTIONS

def _source_signature(path):
    """Return information used to detect modification of an input CSV."""
    path = Path(path)
    stat = path.stat()
    return {
        "path": str(path.resolve()),
        "size": int(stat.st_size),
        "mtime_ns": int(stat.st_mtime_ns),
    }


def _stable_signature(value):
    """Return a deterministic signature for JSON-compatible settings."""
    payload = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        default=str,
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def _atomic_write_json(path, value):
    """Write JSON completely before atomically replacing the destination."""
    path = Path(path)
    temporary_path = path.with_name(path.name + ".tmp")
    with open(temporary_path, "w", encoding="utf-8") as handle:
        json.dump(value, handle, indent=2, sort_keys=True, allow_nan=True)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary_path, path)


def _atomic_savez(path, *, compress, **arrays):
    """Save arrays atomically without serializing the interactive namespace."""
    path = Path(path)
    temporary_path = path.with_name(path.name + ".tmp")
    save_function = np.savez_compressed if compress else np.savez
    with open(temporary_path, "wb") as handle:
        save_function(handle, **arrays)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(temporary_path, path)


def _read_json(path):
    with open(path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _as_jsonable(value):
    """Convert NumPy scalars/arrays to values accepted by json.dump."""
    if isinstance(value, np.ndarray):
        return value.tolist()
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.floating):
        return float(value)
    if isinstance(value, (list, tuple)):
        return [_as_jsonable(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _as_jsonable(item) for key, item in value.items()}
    return value


def _array_from_record(record, key, dtype=float):
    """Restore a one-dimensional NumPy array from a state record."""
    return np.asarray(record[key], dtype=dtype).reshape(-1).copy()


def _iter_complete_fecs_csv(path, usecols=None, *, chunksize):
    """
    Yield complete contiguous fec_id groups from a chunked CSV reader.

    The final group of each chunk is buffered because it may continue in the
    next chunk. A fec_id that reappears after another FEC is rejected.
    """
    pending = None
    emitted_fec_ids = set()
    dtype = {"fec_id": "string", "curve_type": "string"}

    for chunk in pd.read_csv(
        path,
        usecols=usecols,
        chunksize=chunksize,
        dtype=dtype,
    ):
        if chunk.empty:
            continue
        if chunk["fec_id"].isna().any():
            raise ValueError(f"Missing fec_id values were found in {path}.")

        if pending is not None:
            data = pd.concat([pending, chunk], ignore_index=True, copy=False)
            del pending
        else:
            data = chunk

        fec_values = data["fec_id"].astype(str).to_numpy(copy=False)
        boundaries = np.flatnonzero(fec_values[1:] != fec_values[:-1]) + 1
        starts = np.r_[0, boundaries]
        ends = np.r_[boundaries, len(data)]

        for start, end in zip(starts[:-1], ends[:-1]):
            fec_id = str(fec_values[start])
            if fec_id in emitted_fec_ids:
                raise ValueError(
                    f"fec_id {fec_id!r} appears in multiple noncontiguous "
                    f"blocks in {path}. Group the CSV by fec_id first."
                )
            emitted_fec_ids.add(fec_id)
            yield fec_id, data.iloc[start:end].copy()

        pending = data.iloc[starts[-1]:ends[-1]].copy()
        del data, chunk, fec_values, boundaries, starts, ends

    if pending is not None and not pending.empty:
        fec_id = str(pending["fec_id"].iloc[0])
        if fec_id in emitted_fec_ids:
            raise ValueError(
                f"fec_id {fec_id!r} appears in multiple noncontiguous blocks "
                f"in {path}. Group the CSV by fec_id first."
            )
        yield fec_id, pending


def _unique_scalar(trace_df, column, fec_id):
    values = trace_df[column].drop_duplicates()
    if len(values) != 1:
        raise ValueError(
            f"FEC {fec_id!r} contains multiple {column} values: "
            f"{values.tolist()}"
        )
    return values.iloc[0]


def _build_or_load_trace_cache(
    postprocessed_path,
    lctrace_path,
    method,
    *,
    ds,
    chunksize,
    compress,
    rebuild,
):
    """Create disk-backed, trimmed per-FEC arrays using bounded RAM."""
    postprocessed_path = Path(postprocessed_path)
    if not postprocessed_path.exists():
        raise FileNotFoundError(
            f"Postprocessed CSV was not found: {postprocessed_path}"
        )

    sources = {"postprocessed": _source_signature(postprocessed_path)}
    if method == "hmm":
        lctrace_path = Path(lctrace_path)
        if not lctrace_path.exists():
            raise FileNotFoundError(
                f"The HMM method requires this Lc-trace CSV: {lctrace_path}"
            )
        sources["lctraces"] = _source_signature(lctrace_path)
    else:
        sources["lctraces"] = None

    if MANIFEST_PATH.exists() and not rebuild:
        existing = _read_json(MANIFEST_PATH)
        if existing.get("sources") != sources:
            raise RuntimeError(
                "An annotation cache already exists for different input file "
                "versions. If the replacement is intentional, set "
                "REBUILD_TRACE_CACHE = True and rerun the cache cell."
            )

        files_present = True
        for item in existing.get("traces", []):
            files_present &= (CHECKPOINT_DIR / item["trace_file"]).exists()
            if method == "hmm":
                files_present &= (CHECKPOINT_DIR / item["lctrace_file"]).exists()

        if files_present:
            print(
                f"Using existing annotation trace cache with "
                f"{len(existing['traces'])} FECs."
            )
            return existing

        print("The annotation cache is incomplete; rebuilding it.")

    required_columns = [
        "fec_id",
        "rupture_index",
        "curve_type",
        "error_code",
        "trappos1x",
        "diffF",
        "molext",
        "molext_aln",
        "diffF_aln",
    ]
    trace_manifest = []

    print("Building trimmed per-FEC annotation cache...")
    for trace_number, (fec_id, trace_df) in enumerate(
        _iter_complete_fecs_csv(
            postprocessed_path,
            usecols=required_columns,
            chunksize=chunksize,
        )
    ):
        rupture_index = int(_unique_scalar(trace_df, "rupture_index", fec_id))
        curve_type = str(_unique_scalar(trace_df, "curve_type", fec_id))
        error_code = _unique_scalar(trace_df, "error_code", fec_id)

        if curve_type == "S":
            trimmed = trace_df.iloc[:rupture_index + 1]
        elif curve_type == "R":
            trimmed = trace_df.iloc[rupture_index:]
        else:
            raise ValueError(
                f"FEC {fec_id!r} has unsupported curve_type {curve_type!r}."
            )

        trappos = trimmed["trappos1x"].to_numpy(copy=True)
        force = trimmed["diffF"].to_numpy(copy=True)
        molext = trimmed["molext"].to_numpy(copy=True)
        molext_aln = trimmed["molext_aln"].to_numpy(copy=True)
        force_aln = trimmed["diffF_aln"].to_numpy(copy=True)

        trace_file = Path("traces") / f"{trace_number:06d}.npz"
        _atomic_savez(
            CHECKPOINT_DIR / trace_file,
            compress=compress,
            trappos=trappos,
            force=force,
            molext=molext,
            molext_aln=molext_aln,
            force_aln=force_aln,
            trapposlf=CK_filtfilt(trappos, ds),
            flf=CK_filtfilt(force, ds),
            molextlf=CK_filtfilt(molext, ds),
            molext_alnlf=CK_filtfilt(molext_aln, ds),
            force_alnlf=CK_filtfilt(force_aln, ds),
        )

        trace_manifest.append(
            {
                "fec_id": fec_id,
                "curve_type": curve_type,
                "error_code": _as_jsonable(error_code),
                "rupture_index": rupture_index,
                "n_rows": int(len(trimmed)),
                "trace_file": str(trace_file),
                "lctrace_file": str(
                    Path("lctraces") / f"{trace_number:06d}.npz"
                ),
            }
        )
        print(f"Cached {trace_number + 1}: {fec_id}")

        del (
            trace_df,
            trimmed,
            trappos,
            force,
            molext,
            molext_aln,
            force_aln,
        )
        gc.collect()

    if method == "hmm":
        info_by_id = {item["fec_id"]: item for item in trace_manifest}
        cached_lctraces = set()
        for fec_id, lctrace_df in _iter_complete_fecs_csv(
            lctrace_path,
            usecols=["fec_id", "Lc_trace"],
            chunksize=chunksize,
        ):
            if fec_id not in info_by_id:
                del lctrace_df
                continue
            lctrace = lctrace_df["Lc_trace"].to_numpy(copy=True)
            _atomic_savez(
                CHECKPOINT_DIR / info_by_id[fec_id]["lctrace_file"],
                compress=compress,
                lctrace=lctrace,
            )
            cached_lctraces.add(fec_id)
            del lctrace_df, lctrace

        missing = [
            item["fec_id"]
            for item in trace_manifest
            if item["fec_id"] not in cached_lctraces
        ]
        if missing:
            raise KeyError(
                "The Lc-trace CSV is missing these postprocessed FECs: "
                f"{missing}"
            )

    manifest = {
        "version": 1,
        "sources": sources,
        "created": datetime.now().isoformat(),
        "traces": trace_manifest,
    }
    _atomic_write_json(MANIFEST_PATH, manifest)
    print(f"Annotation trace cache complete: {len(trace_manifest)} FECs.")
    return manifest


def _load_trace_arrays(trace_info, *keys):
    path = CHECKPOINT_DIR / trace_info["trace_file"]
    with np.load(path, allow_pickle=False) as saved:
        return tuple(saved[key].copy() for key in keys)


def _load_lctrace(trace_info):
    path = CHECKPOINT_DIR / trace_info["lctrace_file"]
    with np.load(path, allow_pickle=False) as saved:
        return saved["lctrace"].copy()


def _load_or_create_state(manifest, rebuild=False):
    if STATE_PATH.exists() and not rebuild:
        state = _read_json(STATE_PATH)
        if state.get("sources") != manifest["sources"]:
            raise RuntimeError(
                "The annotation state belongs to different input file versions. "
                "Set REBUILD_TRACE_CACHE = True only when intentionally "
                "starting again from replaced input data."
            )
    else:
        state = {
            "version": 1,
            "sources": manifest["sources"],
            "stage_signatures": {},
            "traces": {},
        }

    for item in manifest["traces"]:
        state["traces"].setdefault(item["fec_id"], {})
    _atomic_write_json(STATE_PATH, state)
    return state


def _clear_record_keys(record, keys):
    for key in keys:
        record.pop(key, None)


def _prepare_stage(stage_name, signature, keys_to_clear, force=False):
    previous_signature = annotation_state["stage_signatures"].get(stage_name)
    if force or previous_signature != signature:
        for record in annotation_state["traces"].values():
            _clear_record_keys(record, keys_to_clear)
        annotation_state["stage_signatures"][stage_name] = signature
        _atomic_write_json(STATE_PATH, annotation_state)


def _curation_start_index(flag_key, start_index, stage_label):
    """Resume unfinished work; review all when a completed cell is rerun."""
    if start_index is None:
        unfinished = [
            index
            for index, fec_id in enumerate(fecs)
            if not annotation_state["traces"][fec_id].get(flag_key, False)
        ]
        if unfinished:
            return unfinished[0]
        print(
            f"All FECs already completed {stage_label}. Starting a complete "
            "review from the first FEC."
        )
        return 0

    if isinstance(start_index, str):
        if start_index not in trace_info_by_id:
            raise KeyError(f"Unknown fec_id: {start_index}")
        return fecs.index(start_index)

    index = int(start_index)
    if index < 0 or index >= len(fecs):
        raise IndexError(f"start_index must be between 0 and {len(fecs) - 1}.")
    return index


def unpack_trans_obj(trans_obj):
    """Extract only the small numerical results from FindTransExtensions."""
    total_path = trans_obj.total_direct_path
    tdExt_direct = trans_obj.all_trans_info[total_path]["dExt"]
    tdLc_direct = trans_obj.all_trans_info[total_path]["dLc"]

    keys = list(trans_obj.all_trans_info.keys())
    if len(keys) != 1:
        dExts = [
            trans_obj.all_trans_info[key]["dExt"]
            for key in keys
            if key != total_path
        ]
        dLcs = [
            trans_obj.all_trans_info[key]["dLc"]
            for key in keys
            if key != total_path
        ]
    else:
        dExts = [trans_obj.all_trans_info[key]["dExt"] for key in keys]
        dLcs = [trans_obj.all_trans_info[key]["dLc"] for key in keys]

    # Preserve the original output convention.
    dExts.append(0)
    dLcs.append(0)
    dExts_sum = np.cumsum([0] + dExts[:-1]).tolist()
    dLcs_sum = np.cumsum([0] + dLcs[:-1]).tolist()
    dLcs_sum_complement = np.cumsum(
        [0] + list(np.flip(dLcs[:-1]))
    ).tolist()

    return (
        dExts,
        dLcs,
        dExts_sum,
        dLcs_sum,
        dLcs_sum_complement,
        tdExt_direct,
        tdLc_direct,
    )


def _extension_results(fec_id, trace_info, trans_idxs, trans_params):
    """Calculate transition extensions for one FEC and release the object."""
    d, force = _load_trace_arrays(trace_info, "trapposlf", "flf")
    curve_type = trace_info["curve_type"]
    original_trans_idxs = np.asarray(trans_idxs, dtype=int).reshape(-1)

    if curve_type == "R":
        d_work = np.flip(d)
        f_work = np.flip(force)
        trans_work = len(f_work) - 1 - original_trans_idxs
    else:
        d_work = d
        f_work = force
        trans_work = original_trans_idxs.copy()

    trans_work.sort()
    if len(trans_work) > 1:
        trans_obj = ana.FindTransExtensions(
            fec_id,
            d_work,
            f_work,
            trans_work,
            trans_params=trans_params,
            debug=False,
        )
        trans_obj.run()
        results = unpack_trans_obj(trans_obj)
        del trans_obj
    else:
        results = (0, 0, 0, 0, 0, 0, 0)

    # In the original script, sort() modifies stored indexes only for stretch
    # curves. Relax indexes are transformed/sorted in a separate array.
    stored_trans_idxs = (
        trans_work if curve_type == "S" else original_trans_idxs
    )
    del d, force, d_work, f_work, trans_work
    return stored_trans_idxs, results


def run_transition_detection(parameters, *, force=False):
    """Detect transitions one FEC at a time and checkpoint each result."""
    signature = _stable_signature(
        {
            "sources": manifest["sources"],
            "parameters": parameters,
            "ds_factor": ds_factor,
        }
    )
    downstream_keys = [
        "detected_trans_idxs",
        "transition_trans_idxs",
        "transition_curated",
        "transition_curation_signature",
        "extensions_signature",
        "initial_dExts",
        "initial_dLcs",
        "initial_dExts_sum",
        "initial_dLcs_sum",
        "initial_dLcs_sum_complement",
        "initial_tdExt_direct",
        "initial_tdLc_direct",
        "initial_states",
        "trans_idxs",
        "dExts",
        "dExts_sum",
        "dLcs",
        "dLcs_sum",
        "states",
        "tdExt_direct",
        "tdLc_direct",
        "state_curated",
        "state_curation_signature",
        "final_extensions_signature",
    ]
    _prepare_stage(
        "transition_detection",
        signature,
        downstream_keys,
        force=force,
    )

    for trace_info in manifest["traces"]:
        fec_id = trace_info["fec_id"]
        record = annotation_state["traces"][fec_id]
        if "detected_trans_idxs" in record:
            continue

        (flf,) = _load_trace_arrays(trace_info, "flf")
        if trace_info["curve_type"] == "S":
            force_work = flf
            indexes = np.arange(len(flf))
        else:
            force_work = np.flip(flf)
            indexes = np.flip(np.arange(len(flf)))

        if parameters["rupture_force_detection"] == "hmm":
            lctrace = _load_lctrace(trace_info)
            hmmobj, trans_idxs = ana.find_transitions_hmm(
                indexes,
                force_work,
                lctrace,
                force_cutoff=parameters["force_cutoff"],
                max_states=parameters["max_states"],
                filtering=True,
            )
            del hmmobj, lctrace
        elif parameters["rupture_force_detection"] == "peaks":
            trans_idxs = ana.find_transitions_peaks(
                indexes,
                force_work,
                force_cutoff=parameters["force_cutoff"],
                threshold=parameters["threshold"],
                distance=parameters["distance"],
                window=parameters["window"],
            )
        else:
            raise ValueError("rupture_force_detection must be 'peaks' or 'hmm'.")

        trans_idxs = np.asarray(trans_idxs, dtype=int).reshape(-1)
        record["detected_trans_idxs"] = trans_idxs.tolist()
        _atomic_write_json(STATE_PATH, annotation_state)
        print(f"Transition detection complete: {fec_id}")
        del flf, force_work, indexes, trans_idxs
        gc.collect()


def curate_transitions(parameters, plot_bounds, start_index=None, force=False):
    """Manually curate transitions and checkpoint after every FEC."""
    detection_signature = annotation_state["stage_signatures"].get(
        "transition_detection"
    )
    if detection_signature is None:
        raise RuntimeError("Run transition detection before transition curation.")

    signature = _stable_signature(
        {
            "detection_signature": detection_signature,
            "parameters": parameters,
            "plot_bounds": plot_bounds,
            "var_component": var_component,
        }
    )
    keys_to_clear = [
        "transition_trans_idxs",
        "transition_curated",
        "transition_curation_signature",
        "extensions_signature",
        "initial_dExts",
        "initial_dLcs",
        "initial_dExts_sum",
        "initial_dLcs_sum",
        "initial_dLcs_sum_complement",
        "initial_tdExt_direct",
        "initial_tdLc_direct",
        "initial_states",
        "trans_idxs",
        "dExts",
        "dExts_sum",
        "dLcs",
        "dLcs_sum",
        "states",
        "tdExt_direct",
        "tdLc_direct",
        "state_curated",
        "state_curation_signature",
        "final_extensions_signature",
    ]
    _prepare_stage(
        "transition_curation",
        signature,
        keys_to_clear,
        force=force,
    )

    current_index = _curation_start_index(
        "transition_curated",
        start_index,
        "transition curation",
    )

    while current_index < len(fecs):
        fec_id = fecs[current_index]
        trace_info = trace_info_by_id[fec_id]
        record = annotation_state["traces"][fec_id]

        if record.get("transition_curated", False):
            old_trans_idxs = _array_from_record(
                record,
                "transition_trans_idxs",
                dtype=int,
            )
        else:
            old_trans_idxs = _array_from_record(
                record,
                "detected_trans_idxs",
                dtype=int,
            )

        d, dlf, force, flf = _load_trace_arrays(
            trace_info,
            "molext_aln",
            "molext_alnlf",
            "force_aln",
            "force_alnlf",
        )
        lctrace = (
            _load_lctrace(trace_info)
            if parameters["rupture_force_detection"] == "hmm"
            else None
        )

        editor = ana.EditTransitions(
            fec_id,
            dlf,
            flf,
            d,
            force,
            old_trans_idxs,
            plot_bounds,
            parameters,
            var_component=var_component,
            lctrace=lctrace,
            curve_type=trace_info["curve_type"],
        )
        continue_decision = editor.run()
        new_trans_idxs = np.asarray(editor.trans_idxs, dtype=int).reshape(-1)

        changed = not np.array_equal(new_trans_idxs, old_trans_idxs)
        record["transition_trans_idxs"] = new_trans_idxs.tolist()
        record["transition_curated"] = True
        record["transition_curation_signature"] = signature
        record["transition_curated_at"] = datetime.now().isoformat()

        if changed:
            _clear_record_keys(
                record,
                [
                    "extensions_signature",
                    "initial_dExts",
                    "initial_dLcs",
                    "initial_dExts_sum",
                    "initial_dLcs_sum",
                    "initial_dLcs_sum_complement",
                    "initial_tdExt_direct",
                    "initial_tdLc_direct",
                    "initial_states",
                    "trans_idxs",
                    "dExts",
                    "dExts_sum",
                    "dLcs",
                    "dLcs_sum",
                    "states",
                    "tdExt_direct",
                    "tdLc_direct",
                    "state_curated",
                    "state_curation_signature",
                    "final_extensions_signature",
                ],
            )

        _atomic_write_json(STATE_PATH, annotation_state)
        print(
            f"Transition checkpoint saved: {fec_id} "
            f"({current_index + 1}/{len(fecs)})"
        )

        del (
            d,
            dlf,
            force,
            flf,
            lctrace,
            editor,
            old_trans_idxs,
            new_trans_idxs,
        )
        plt.close("all")
        gc.collect()

        if continue_decision == "c":
            current_index += 1
        elif continue_decision == "r":
            if current_index == 0:
                print("No previous FEC. Remaining on the first FEC.")
            else:
                current_index -= 1
        else:
            print(
                f"Unrecognized decision {continue_decision!r}; remaining on "
                "the current FEC."
            )


def calculate_extensions_and_initial_states(trans_params, *, force=False):
    """Calculate transition sizes and initial WLC states one FEC at a time."""
    curation_signature = annotation_state["stage_signatures"].get(
        "transition_curation"
    )
    if curation_signature is None:
        raise RuntimeError("Run transition curation before extension analysis.")

    signature = _stable_signature(
        {
            "transition_curation_signature": curation_signature,
            "trans_params": trans_params,
            "aligned": aligned,
            "end_alignment": end_alignment,
            "WLCp": WLCp,
            "var_component": var_component,
        }
    )
    keys_to_clear = [
        "extensions_signature",
        "initial_dExts",
        "initial_dLcs",
        "initial_dExts_sum",
        "initial_dLcs_sum",
        "initial_dLcs_sum_complement",
        "initial_tdExt_direct",
        "initial_tdLc_direct",
        "initial_states",
        "trans_idxs",
        "dExts",
        "dExts_sum",
        "dLcs",
        "dLcs_sum",
        "states",
        "tdExt_direct",
        "tdLc_direct",
        "state_curated",
        "state_curation_signature",
        "final_extensions_signature",
    ]
    _prepare_stage("initial_extensions", signature, keys_to_clear, force=force)

    for trace_info in manifest["traces"]:
        fec_id = trace_info["fec_id"]
        record = annotation_state["traces"][fec_id]
        if record.get("extensions_signature") == signature:
            continue
        if not record.get("transition_curated", False):
            raise RuntimeError(
                f"FEC {fec_id!r} has not completed transition curation."
            )

        transition_trans_idxs = _array_from_record(
            record,
            "transition_trans_idxs",
            dtype=int,
        )
        stored_trans_idxs, results = _extension_results(
            fec_id,
            trace_info,
            transition_trans_idxs,
            trans_params,
        )
        (
            dExts,
            dLcs,
            dExts_sum,
            dLcs_sum,
            dLcs_sum_complement,
            tdExt_direct,
            tdLc_direct,
        ) = results

        if aligned:
            reference_lc = WLCp[var_component][1]
            if end_alignment:
                states = np.flip(
                    reference_lc - np.asarray(dLcs_sum_complement)
                )
            else:
                states = reference_lc + np.asarray(dLcs_sum)
        else:
            states = np.nan

        initial_values = {
            "initial_dExts": dExts,
            "initial_dLcs": dLcs,
            "initial_dExts_sum": dExts_sum,
            "initial_dLcs_sum": dLcs_sum,
            "initial_dLcs_sum_complement": dLcs_sum_complement,
            "initial_tdExt_direct": tdExt_direct,
            "initial_tdLc_direct": tdLc_direct,
            "initial_states": states,
        }
        for key, value in initial_values.items():
            record[key] = _as_jsonable(value)

        record["transition_trans_idxs"] = stored_trans_idxs.tolist()
        record["trans_idxs"] = stored_trans_idxs.tolist()
        record["dExts"] = _as_jsonable(dExts)
        record["dExts_sum"] = _as_jsonable(dExts_sum)
        record["dLcs"] = _as_jsonable(dLcs)
        record["dLcs_sum"] = _as_jsonable(dLcs_sum)
        record["states"] = _as_jsonable(states)
        record["tdExt_direct"] = _as_jsonable(tdExt_direct)
        record["tdLc_direct"] = _as_jsonable(tdLc_direct)
        record["extensions_signature"] = signature
        _atomic_write_json(STATE_PATH, annotation_state)
        print(f"Initial transition extensions complete: {fec_id}")

        del transition_trans_idxs, stored_trans_idxs, results, states
        gc.collect()


def curate_states(parameters, plot_bounds, start_index=None, force=False):
    """Manually curate WLC states and checkpoint after every FEC."""
    if not aligned:
        print("State curation skipped because aligned=False.")
        return

    extension_signature = annotation_state["stage_signatures"].get(
        "initial_extensions"
    )
    if extension_signature is None:
        raise RuntimeError("Calculate initial extensions before state curation.")

    signature = _stable_signature(
        {
            "extension_signature": extension_signature,
            "parameters": parameters,
            "plot_bounds": plot_bounds,
            "WLCp": WLCp,
            "var_component": var_component,
            "end_alignment": end_alignment,
        }
    )
    _prepare_stage(
        "state_curation",
        signature,
        [
            "trans_idxs",
            "dExts",
            "dExts_sum",
            "dLcs",
            "dLcs_sum",
            "states",
            "tdExt_direct",
            "tdLc_direct",
            "state_curated",
            "state_curation_signature",
            "final_extensions_signature",
        ],
        force=force,
    )

    current_index = _curation_start_index(
        "state_curated",
        start_index,
        "state curation",
    )

    while current_index < len(fecs):
        fec_id = fecs[current_index]
        trace_info = trace_info_by_id[fec_id]
        record = annotation_state["traces"][fec_id]

        if record.get("state_curated", False):
            trans_idxs = _array_from_record(record, "trans_idxs", dtype=int)
            states = _array_from_record(record, "states", dtype=float)
            dLcs = _array_from_record(record, "dLcs", dtype=float)
            dLcs_sum = _array_from_record(record, "dLcs_sum", dtype=float)
        else:
            trans_idxs = _array_from_record(
                record,
                "transition_trans_idxs",
                dtype=int,
            )
            states = np.asarray(record["initial_states"], dtype=float).reshape(-1)
            dLcs = np.asarray(record["initial_dLcs"], dtype=float).reshape(-1)
            dLcs_sum = np.asarray(
                record["initial_dLcs_sum"],
                dtype=float,
            ).reshape(-1)

        d, dlf, force, flf = _load_trace_arrays(
            trace_info,
            "molext_aln",
            "molext_alnlf",
            "force_aln",
            "force_alnlf",
        )

        old_trans_idxs = trans_idxs.copy()
        old_states = states.copy()
        old_dLcs = dLcs.copy()
        old_dLcs_sum = dLcs_sum.copy()

        editor = ana.EditStates(
            fec_id,
            dlf,
            flf,
            d,
            force,
            trans_idxs,
            parameters,
            states,
            WLCp[var_component][1],
            trace_info["error_code"],
            plot_bounds,
            *WLCp,
            var_lc_component=var_component,
            lc_trace=None,
            curve_type=trace_info["curve_type"],
        )
        continue_decision = editor.run()

        new_trans_idxs = np.asarray(editor.trans_idxs, dtype=int).reshape(-1)
        new_states = np.asarray(editor.states).reshape(-1)
        new_dLcs_sum = np.asarray(editor.dLcs_sum).reshape(-1)
        new_dLcs = np.asarray(editor.dLcs).reshape(-1)
        changed = not (
            np.array_equal(new_trans_idxs, old_trans_idxs)
            and np.array_equal(new_states, old_states, equal_nan=True)
            and np.array_equal(new_dLcs, old_dLcs, equal_nan=True)
            and np.array_equal(new_dLcs_sum, old_dLcs_sum, equal_nan=True)
        )

        record["trans_idxs"] = new_trans_idxs.tolist()
        record["states"] = _as_jsonable(new_states)
        record["dLcs_sum"] = _as_jsonable(new_dLcs_sum)
        record["dLcs"] = _as_jsonable(new_dLcs)
        record.setdefault("dExts", record["initial_dExts"])
        record.setdefault("dExts_sum", record["initial_dExts_sum"])
        record.setdefault("tdExt_direct", record["initial_tdExt_direct"])
        record.setdefault("tdLc_direct", record["initial_tdLc_direct"])
        record["state_curated"] = True
        record["state_curation_signature"] = signature
        record["state_curated_at"] = datetime.now().isoformat()
        if changed:
            record.pop("final_extensions_signature", None)

        _atomic_write_json(STATE_PATH, annotation_state)
        print(
            f"State checkpoint saved: {fec_id} "
            f"({current_index + 1}/{len(fecs)})"
        )

        del (
            d,
            dlf,
            force,
            flf,
            trans_idxs,
            states,
            dLcs,
            dLcs_sum,
            old_trans_idxs,
            old_states,
            old_dLcs,
            old_dLcs_sum,
            new_trans_idxs,
            new_states,
            new_dLcs,
            new_dLcs_sum,
            editor,
        )
        plt.close("all")
        gc.collect()

        if continue_decision == "c":
            current_index += 1
        elif continue_decision == "r":
            if current_index == 0:
                print("No previous FEC. Remaining on the first FEC.")
            else:
                current_index -= 1
        else:
            print(
                f"Unrecognized decision {continue_decision!r}; remaining on "
                "the current FEC."
            )


def recalculate_final_extensions(trans_params, *, force=False):
    """Recalculate mirror-position extensions using the final transition indexes."""
    dependency = annotation_state["stage_signatures"].get(
        "state_curation" if aligned else "initial_extensions"
    )
    if dependency is None:
        raise RuntimeError("Complete the preceding annotation stage first.")

    signature = _stable_signature(
        {"dependency": dependency, "trans_params": trans_params}
    )
    _prepare_stage(
        "final_extensions",
        signature,
        ["final_extensions_signature"],
        force=force,
    )

    for trace_info in manifest["traces"]:
        fec_id = trace_info["fec_id"]
        record = annotation_state["traces"][fec_id]
        if record.get("final_extensions_signature") == signature:
            continue
        if aligned and not record.get("state_curated", False):
            raise RuntimeError(f"FEC {fec_id!r} has not completed state curation.")

        trans_idxs = _array_from_record(record, "trans_idxs", dtype=int)
        stored_trans_idxs, results = _extension_results(
            fec_id,
            trace_info,
            trans_idxs,
            trans_params,
        )
        dExts, _, dExts_sum, _, _, _, _ = results
        record["trans_idxs"] = stored_trans_idxs.tolist()
        record["dExts"] = _as_jsonable(dExts)
        record["dExts_sum"] = _as_jsonable(dExts_sum)
        record["final_extensions_signature"] = signature
        _atomic_write_json(STATE_PATH, annotation_state)
        print(f"Final mirror-position extensions complete: {fec_id}")

        del trans_idxs, stored_trans_idxs, results
        gc.collect()


def save_annotation_plots(plot_bounds):
    """Save one final annotation plot at a time and close its figure."""
    final_signature = annotation_state["stage_signatures"].get(
        "final_extensions"
    )
    if final_signature is None:
        raise RuntimeError("Recalculate final extensions before plotting.")

    for trace_info in manifest["traces"]:
        fec_id = trace_info["fec_id"]
        record = annotation_state["traces"][fec_id]
        if record.get("final_extensions_signature") != final_signature:
            raise RuntimeError(f"FEC {fec_id!r} is missing final extensions.")

        if aligned:
            d, dlf, force, flf = _load_trace_arrays(
                trace_info,
                "molext_aln",
                "molext_alnlf",
                "force_aln",
                "force_alnlf",
            )
        else:
            d, dlf, force, flf = _load_trace_arrays(
                trace_info,
                "molext",
                "molextlf",
                "force",
                "flf",
            )

        states = np.asarray(record["states"])
        trans_idxs = _array_from_record(record, "trans_idxs", dtype=int)
        fplt.plot_individual_fec(
            dlf,
            flf,
            fec_id,
            "black",
            plot_bounds[0],
            plot_bounds[1],
            str(ANNOTATE_PICS_DIR / f"{fec_id}.png"),
            *WLCp,
            var_component=var_component,
            distances_hf=d,
            forces_hf=force,
            scatter=False,
            annot=False,
            savefig=True,
            rupture_index=False,
            lcstates=states,
            states_end_indexes=trans_idxs,
            lc_trajectory=False,
        )
        plt.close("all")
        print(f"Saved annotation plot: {fec_id}")
        del d, dlf, force, flf, states, trans_idxs
        gc.collect()


def _broadcast_annotation_value(value, length, column):
    array = np.asarray(value)
    if array.ndim == 0:
        return np.full(length, array.item())
    array = array.reshape(-1)
    if len(array) != length:
        raise ValueError(
            f"Annotation column {column!r} has {len(array)} values; "
            f"expected {length}."
        )
    return array


def write_annotation_csv(output_path):
    """Write annotations one FEC at a time, then atomically replace the CSV."""
    output_path = Path(output_path)
    temporary_path = output_path.with_name(output_path.name + ".tmp")
    columns = [
        "trans_idxs",
        "dExts",
        "dExts_sum",
        "dLcs",
        "dLcs_sum",
        "states",
        "tdExt_direct",
        "tdLc_direct",
        "fec_id",
    ]
    pd.DataFrame(columns=columns).to_csv(temporary_path, index=False)

    final_signature = annotation_state["stage_signatures"].get(
        "final_extensions"
    )
    for trace_info in manifest["traces"]:
        fec_id = trace_info["fec_id"]
        record = annotation_state["traces"][fec_id]
        if record.get("final_extensions_signature") != final_signature:
            raise RuntimeError(f"FEC {fec_id!r} is not ready for final output.")

        trans_idxs = _array_from_record(record, "trans_idxs", dtype=int)
        if trace_info["curve_type"] == "R":
            trans_idxs = np.flip(trans_idxs)
        length = len(trans_idxs)

        frame = pd.DataFrame({"trans_idxs": trans_idxs})
        for column in columns[1:-1]:
            frame[column] = _broadcast_annotation_value(
                record[column],
                length,
                column,
            )
        frame["fec_id"] = fec_id
        frame.to_csv(
            temporary_path,
            mode="a",
            header=False,
            index=False,
            columns=columns,
        )
        print(f"Wrote annotation data: {fec_id}")
        del frame, trans_idxs

    os.replace(temporary_path, output_path)
    print(f"Saved: {output_path}")


def save_metadata(metadata_path, parameters, trans_params):
    """Save annotation and transition-extension settings."""
    with open(metadata_path, "w", encoding="utf-8") as handle:
        handle.write(
            f"{folder} annotation was performed on: {datetime.now()}\n\n"
        )
        handle.write("The following parameters were used:\n")
        handle.write(
            "Method for transition detection: "
            f"{parameters['rupture_force_detection']}\n"
        )
        handle.write(f"force_cutoff: {parameters['force_cutoff']}\n")

        if parameters["rupture_force_detection"] == "peaks":
            handle.write(f"threshold: {parameters['threshold']}\n")
            handle.write(f"distance: {parameters['distance']}\n")
            handle.write(f"window: {parameters['window']}\n\n")
        else:
            handle.write(f"max_states: {parameters['max_states']}\n\n")

        handle.write("Parameters for finding Lc changes:\n")
        handle.write(f"Lp: {trans_params['Lp']}\n")
        handle.write(f"S: {trans_params['S']}\n")
        handle.write(f"Min points for linear fit: {trans_params['nfit']}\n")
        handle.write(f"Min points for averaging: {trans_params['navg']}\n")
        handle.write(
            f"Force range for averaging: {trans_params['FAvgRange']}\n"
        )
        handle.write(
            f"Force range for linear fitting: {trans_params['FFitRange']}\n"
        )
        handle.write(
            f"Padding between transitions: {trans_params['padding']}\n"
        )
        handle.write(
            "\nPer-FEC recovery state was retained at:\n"
            f"{STATE_PATH}\n"
        )
    print(f"Saved: {metadata_path}")


# %% DEFINE GENERAL VARIABLES

folder = (
    "260906_BiotBact1_1016-601-Bact2_269NBsaILig_STdimerTArich_90mMKCl_2500uMMgCl2_15ng_ul_TYRNA_1umBeads"
)

# Available methods: "peaks" or "hmm".
rupture_force_detection = "peaks"

if rupture_force_detection == "peaks":
    parameters = {
        "rupture_force_detection": "peaks",
        "force_cutoff": 1,
        "threshold": 0.5,
        "distance": 5,
        "window": 5,
    }
elif rupture_force_detection == "hmm":
    parameters = {
        "rupture_force_detection": "hmm",
        "force_cutoff": 2,
        "max_states": 10,
    }
else:
    raise ValueError("rupture_force_detection must be 'peaks' or 'hmm'.")

WLCp = ([50, 0.7854, 1200], [0.65, 0.01296])
aligned = True
end_alignment = True
var_component = 0

# Visualization/downsampling.
ds_factor = 25
TRANSITION_PLOT_BOUNDS = [[0.45, 1.2], [-1, 40]]
STATE_PLOT_BOUNDS = [[0.5, 1], [-1, 35]]
FINAL_PLOT_BOUNDS = [[0.5, 1], [-2, 40]]

# Chunk/checkpoint settings.
CSV_CHUNKSIZE = 500_000
COMPRESS_CHECKPOINTS = False
REBUILD_TRACE_CACHE = False

# Extension-calculation settings.
trans_params = {
    "nfit": 22,
    "navg": 2,
    "FAvgRange": 0.05,
    "FFitRange": 1,
    "padding": 3,
    "Lp": 50,
    "S": 1200,
}


# %% DEFINE PATHS

POSTPROCESSED_PATH = Path("postprocess") / f"{folder}_postprocessed.csv"
LCTRACE_PATH = Path("per_pointLc") / f"{folder}_lctraces.csv"
ANNOTATE_DIR = Path("annotate")
ANNOTATE_PICS_DIR = ANNOTATE_DIR / "annotate_pics"
ANNOTATION_OUTPUT_PATH = ANNOTATE_DIR / f"{folder}_annotated_states.csv"
METADATA_PATH = ANNOTATE_DIR / f"{folder}_annotation_metadata.txt"

CHECKPOINT_DIR = ANNOTATE_DIR / "checkpoints" / folder
TRACE_CACHE_DIR = CHECKPOINT_DIR / "traces"
LCTRACE_CACHE_DIR = CHECKPOINT_DIR / "lctraces"
MANIFEST_PATH = CHECKPOINT_DIR / "manifest.json"
STATE_PATH = CHECKPOINT_DIR / "state.json"

ANNOTATE_DIR.mkdir(parents=True, exist_ok=True)
ANNOTATE_PICS_DIR.mkdir(parents=True, exist_ok=True)
TRACE_CACHE_DIR.mkdir(parents=True, exist_ok=True)
LCTRACE_CACHE_DIR.mkdir(parents=True, exist_ok=True)


# %% BUILD OR LOAD PER-FEC TRACE CACHE

manifest = _build_or_load_trace_cache(
    POSTPROCESSED_PATH,
    LCTRACE_PATH,
    rupture_force_detection,
    ds=ds_factor,
    chunksize=CSV_CHUNKSIZE,
    compress=COMPRESS_CHECKPOINTS,
    rebuild=REBUILD_TRACE_CACHE,
)
annotation_state = _load_or_create_state(
    manifest,
    rebuild=REBUILD_TRACE_CACHE,
)
trace_info_by_id = {item["fec_id"]: item for item in manifest["traces"]}
fecs = [item["fec_id"] for item in manifest["traces"]]


# %% FIND TRANSITIONS

run_transition_detection(parameters, force=False)


# %% TRANSITIONS MANUAL CURATION

# Partial work resumes at the first unfinished FEC. If all FECs are already
# curated, rerunning this cell reviews every FEC again from the beginning while
# retaining the saved transition indexes.
curate_transitions(
    parameters,
    TRANSITION_PLOT_BOUNDS,
    force=False,
)


# %% FIND RIP EXTENSIONS AND INITIAL STATES

calculate_extensions_and_initial_states(trans_params, force=False)


# %% STATES MANUAL CURATION

# This has the same resume/review behavior as transition curation.
if aligned:
    curate_states(
        parameters,
        STATE_PLOT_BOUNDS,
        force=False,
    )


# %% RECALCULATE MIRROR-POSITION EXTENSIONS WITH FINAL TRANSITIONS

recalculate_final_extensions(trans_params, force=False)


# %% PLOT RIPS AND WLCS

save_annotation_plots(FINAL_PLOT_BOUNDS)


# %% WRITE FINAL ANNOTATION CSV

write_annotation_csv(ANNOTATION_OUTPUT_PATH)


# %% SAVE METADATA

save_metadata(METADATA_PATH, parameters, trans_params)


# %% FINISHED

plt.close("all")
gc.collect()
print("Annotation finished successfully. No dill session dump is required.")
